### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by chars32** [fiveisprime/marvel-api#7]
Sorry I am new in this, i have two questions:

in what file i write my apikey ???
how i start the app ???

**Comment by fiveisprime** [comment]
Hi!

This isn't an app, you'll have to create an app to use this module. You can put
your API key in any file you choose to. :)

I suggest starting out by creating a new directory and running `$ npm init` to
create a package.json followed by `$ npm install marvel-api --save` to install
this module into your newly created app.

From there, create a file named `index.js` and put your custom code in there.
Run the application by running `$ node index` or `$ node .`. You can use this
module exactly like the examples in the readme here.
